FROM python:3.9

RUN apt-get update && apt-get install -y \
    curl \
    wget \
    git \
    vim \
    build-essential \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN pip install torch torchvision pillow

COPY model.pt .
COPY inference.py .
COPY imagenet_labels.json .

ENTRYPOINT ["python", "inference.py"]
